### ISSUE TITLE
Script is taking too much ms over 0.10ms on low pcs..

### ISSUE THREAD

**Issue by Tinky124** [propstg/blarglewash#2]
This code has problem with loop maybe to add check distance on marker or something like that so i doesnt always loop..

```
function startMainLoop()
    while true do
        Citizen.Wait(10)

        local playerPed = PlayerPedId()

        if IsPedInAnyVehicle(playerPed, true) then
            for i = 1, #Config.Locations do
                handleLocation(i, playerPed)
            end
        else
            Citizen.Wait(1000)
        end
    end
end
```

**Comment by propstg** [comment]
When does the warning actually appear?

1. Constantly, even when the player is not near a car wash? 
2. When the player is close enough to the car wash to show the notification? 
3. Only when the car wash is actually running?
4. Something else?

**Comment by Tinky124** [comment]
Constantly taking 0.07ms on foot, script doesnt have distance check marker.. if it have its too much distance, 20 distance is good for loop only or 15 maybe add config to drawmarker distance, when in car 0.12ms constantly even is player not near a car wash.. 
Warning comes when player is close enought to the car wash to show the notificaiton.
I fixed when player is not car so i doesnt loop but when in player in vehicle RIP FPS.

**Comment by Tinky124** [comment]
but yea this code is very old to loop...

**Comment by propstg** [comment]
Thanks for the information. I'll take a look when I get a chance.

> but yea this code is very old to loop...

I'm not sure what you mean by this?

**Comment by Tinky124** [comment]
i mean that old code, you didnt updated very long time ago... 2 years xD

**Comment by propstg** [comment]
Hey @Tinky124, I made some improvements to the script, if you want to give it a try before I merge it. https://github.com/propstg/blarglewash/pull/3

**Comment by Tinky124** [comment]
Thanks its fixed now, much better code
